pulumi_projects:
  "001575623345": "prima-it-pulumi-state"
  "815911007681": "pulumi-uk-pulumi-state"
  "595659439703": "prima-common-pulumi-state"
  "199959896441": "pulumi-state-bucket"
  "921023736012": "prima-claims-pulumi-state-staging"
  "441430380389": "prima-claims-pulumi-state-production"
  "222436446022": "prima-customer-mgmt-pulumi-state-staging"
  "405533318024": "prima-customer-mgmt-pulumi-state-production"
  "279066465364": "prima-resources-pulumi-state"
  "329599635286": "prima-resources-pulumi-state-staging"
  "970547380306": "prima-msa-vpn-pulumi-state-production"
  "790238256018": "prima-root-pulumi-state"
  "675683048970": "prima-ania-pulumi-state-production"
  "851725473830": "prima-policy-management-pulumi-state-production"
  "275274546462": "prima-shared-services-pulumi-state-staging"
  "049818842165": "prima-networking-pulumi-state"
  "257028423174": "prima-intermediaries-pulumi-state-staging"
  "default": "undefined"
